targets:
  $default:
    builders:
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/features/**
            - lib/core/**/models/**
            - modules/**/
