name: weather_app

packages:
  - ./
  - modules/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.8.1 <4.0.0'
      flutter: "3.35.4"

    dependencies:
      # Core Framework Dependencies
      collection: 1.19.1
      equatable: 2.0.7
      intl: 0.20.2

      # State Management
      bloc: 8.1.4
      flutter_bloc: 8.1.5
      flutter_riverpod: 2.6.1

      # Navigation
      go_router: 16.2.4

      # Networking
      dio: 5.4.3+1
      connectivity_plus: 4.0.1

      # Firebase Services
      firebase_core: 4.0.0
      firebase_messaging: 16.0.0
      firebase_analytics: 12.0.0
      firebase_crashlytics: 5.0.0

      # UI Components
      badges: 3.1.2
      lottie: 3.3.1
      shimmer: 3.0.0
      flutter_svg: 2.0.17
      pin_code_fields: 8.0.1
      pull_to_refresh: 2.0.0
      percent_indicator: 4.2.5
      cached_network_image: 3.3.1

      # Device Features
      camera: 0.10.5+9
      local_auth: 2.3.0
      local_auth_darwin: 1.6.0
      device_info_plus: 11.4.0
      package_info_plus: 8.3.0
      permission_handler: 12.0.1
      file_picker: 10.2.1
      image_picker: 1.1.2

      # Storage and Preferences
      path_provider: 2.1.5
      shared_preferences: 2.2.2
      path: 1.9.1

      # Utilities
      image: 4.5.4
      restart_app: 1.3.2
      share_plus: 11.0.0
      in_date_utils: 1.2.1
      flutter_multi_formatter: 2.13.7
      mask_text_input_formatter: 2.9.0
      url_launcher: 6.3.2
      flutter_native_splash: 2.4.0
      flutter_local_notifications: 18.0.1
      
      # Code Generation and Annotations
      slang: 4.8.1
      slang_flutter: 4.8.0
      json_annotation: 4.9.0
      freezed_annotation: 3.1.0

    dev_dependencies:
      # Code Generation
      freezed: 3.2.3
      build_runner: 2.8.0
      json_serializable: 6.11.1
      slang_build_runner: 4.8.1
      flutter_gen_runner: 5.12.0
      
      # Linting and Formatting
      flutter_lints: 6.0.0
      import_sorter: 4.6.0
      
      # Build Tools
      flutter_launcher_icons: 0.13.1
