name: weather_uikit
description: UI kit
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: "3.35.4"

dependencies:
  flutter:
    sdk: flutter

  # UI Widgets
  badges: 3.1.2
  lottie: 3.3.1
  shimmer: 3.0.0
  flutter_svg: 2.0.17
  pull_to_refresh: 2.0.0
  pin_code_fields: 8.0.1
  percent_indicator: 4.2.5
  cached_network_image: 3.3.1

  # Utilities
  intl: 0.20.2
  in_date_utils: 1.2.1
  flutter_multi_formatter: 2.13.7
  mask_text_input_formatter: 2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting and Formatting
  flutter_lints: 6.0.0
  import_sorter: 4.6.0
  
  # Code Generation
  build_runner: 2.8.0
  flutter_gen_runner: 5.12.0

flutter_gen:
  output: lib/gen
  integrations:
    lottie: true
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: UikitAssets
      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons16/
    - assets/icons20/
    - assets/icons24/
    - assets/icons32/
    - assets/icons40/
    - assets/icons96/
    - assets/icons200/
    - assets/menu/
    - assets/flags/

  fonts:
    - family: AeonikPro
      fonts:
        - asset: assets/fonts/AeonikPro-Regular.otf
          weight: 400
        - asset: assets/fonts/AeonikPro-Medium.otf
          weight: 500
        - asset: assets/fonts/AeonikPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/AeonikPro-Bold.otf
          weight: 700
