name: city_search
description: "Search city"

version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.35.4"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  import_sorter: 4.6.0
  build_runner: 2.8.0
  flutter_gen_runner: 5.12.0
  freezed: 3.2.3
  json_serializable: 6.11.1

flutter:
  module:
    androidX: true
    androidPackage: uz.paradigm.weather
    iosBundleIdentifier: uz.paradigm.weather
