name: core
description: "A new Flutter module project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: "3.35.4"

dependencies:
  flutter:
    sdk: flutter

  # Core Framework Dependencies
  collection: 1.19.1
  equatable: 2.0.7
  rxdart: 0.28.0

  # State Management
  bloc: 8.1.4
  flutter_bloc: 8.1.5
  flutter_riverpod: 2.6.1

  # Navigation
  go_router: 16.2.4

  # Networking
  dio: 5.9.0
  connectivity_plus: 4.0.1
  logger: 2.6.1
  
  # Storage
  shared_preferences: 2.2.2
  path_provider: 2.1.5

  # Authentication
  local_auth: 2.3.0
  local_auth_darwin: 1.6.0

  # Device Features
  device_info_plus: 11.4.0
  package_info_plus: 8.3.0
  permission_handler: 12.0.1
  file_picker: 10.2.1
  image_picker: 1.1.2

  # Firebase
  firebase_remote_config: 6.0.2

  # Utilities
  alice: 1.0.0
  alice_dio: 1.0.7
  share_plus: 11.0.0
  restart_app: 1.3.2
  url_launcher: 6.3.2
  path: 1.9.1

  # Code Generation and Annotations
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: 2.8.0
  freezed: 3.2.3
  json_serializable: 6.11.1
  flutter_gen_runner: 5.12.0 

  # Linting and Formatting
  flutter_lints: 6.0.0
  import_sorter: 4.6.0

flutter:
  module:
    androidX: true
    androidPackage: uz.paradigm.core
    iosBundleIdentifier: uz.paradigm.core
